setup.py
stream_chat/__init__.py
stream_chat/__pkg__.py
stream_chat/client.py

Fix setup.py importing project dependencies

---

stream_chat/__pkg__.py
stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/conftest.py
stream_chat/tests/test_channel.py
stream_chat/tests/test_client.py

Adds message and user moderation flagging and unflagging methods

Add flag and unflag methods

---

stream_chat/client.py
stream_chat/tests/test_client.py

Addresses https://github.com/GetStream/stream-chat-python/issues/6.

Fix PUT call in update_channel_type

---

.travis.yml
setup.py
stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/test_channel.py
stream_chat/tests/test_client.py

add channel.hide|show methods / fix tests

Add methods

---

stream_chat/client.py

for blablacar, hosted on dublin.
Other changes are coming from black.

Support customizing base url

---

CHANGELOG
setup.py

We already test with 3.8 so added support to setup.

Add 3.8 support to setup

---

.travis.yml
README.md
pyproject.toml
stream_chat/__init__.py
stream_chat/channel.py
stream_chat/exceptions.py
stream_chat/tests/conftest.py
stream_chat/tests/test_channel.py

* Improve travis setup
* Really check black
* Handle deprecation of black flag
* Trim whitespace readme
Side, increased runners to 4 for this repo.

CI improvements

---

CHANGELOG
stream_chat/client.py
stream_chat/tests/test_channel.py

Set a generic user-agent for bot detection

---

stream_chat/channel.py
stream_chat/client.py

After going through few posts and threads, literals `{}` are better in some cases compared to `dict()`.
In these cases, i felt using curly braces are better.

Prefer literals over constructor for dicts

---

stream_chat/channel.py
stream_chat/client.py

Further simplications for literals

---

.gitignore
stream_chat/client.py
stream_chat/tests/conftest.py
stream_chat/tests/test_client.py

Added Command methods + Tests to Client:
- CreateCommand
- GetCommand
- ListCommands
- UpdateCommand
- DeleteCommand

Custom command crud

---

stream_chat/client.py
stream_chat/tests/test_client.py

Adds bindings for blocklist creation, updating, listing/retrieval, and deletion.

Add blocklist CRUD

---

CHANGELOG
stream_chat/__pkg__.py

Prepare v1.7.0

---

setup.py
stream_chat/tests/async_chat/test_channel.py
stream_chat/tests/test_channel.py

Add async speedups

---

stream_chat/async_chat/channel.py
stream_chat/async_chat/client.py
stream_chat/base/channel.py
stream_chat/base/exceptions.py
stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

As per issue #45, migrating to f string.

Migrate to f string.

---

setup.py
stream_chat/base/client.py

Bump pyjwt to 2.x

---

stream_chat/base/client.py

Add extra claims into token creation

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

Add custom permission/rotes

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

This PR adds support for the GetRateLimits endpoint which returns rate limit quotas and usage.

support GetRateLimits

---

.github/workflows/ci.yml
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

Use max-parallel for conflicting tests

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

Feature: Search improvements

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py

Make campaign schedule time optional, assumes now

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/tests/test_client.py

This PR updates REST API of permissions CRUD

Updated permissions REST API

---

stream_chat/async_chat/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

This PR updates permission-related API and corresponding tests

Permissions API follow-up changes

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_channel.py
stream_chat/tests/test_channel.py

Add tests for exports

---

stream_chat/async_chat/channel.py
stream_chat/base/channel.py
stream_chat/channel.py

Add optional messages for members

---

stream_chat/async_chat/channel.py
stream_chat/base/channel.py
stream_chat/channel.py
stream_chat/tests/async_chat/test_channel.py
stream_chat/tests/test_channel.py

This PR adds support for assign_roles channel feature

Add assign_roles support

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

Added functionality to retrieve/review flag reports.

[CHAT-2693] Add flag reports api

---

.github/CODEOWNERS
.github/workflows/ci.yml
.github/workflows/initiate_release.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
.versionrc.js
CHANGELOG.md
pyproject.toml
scripts/get_changelog_diff.js
stream_chat/tests/async_chat/test_channel.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py
stream_chat/tests/utils.py

- we need to add secrets.PYPI_TOKEN key
- update tests due to new pytest-async release
- refactor unstable test a little bit

ci: add automation to python repo

---

.github/workflows/ci.yml
README.md
stream_chat/async_chat/channel.py
stream_chat/async_chat/client.py
stream_chat/base/channel.py
stream_chat/base/client.py
stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/async_chat/test_channel.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_channel.py
stream_chat/tests/test_client.py

feat: add full feature parity

---

stream_chat/async_chat/client.py
stream_chat/client.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/test_client.py

feat: swappable http client

---

stream_chat/async_chat/client.py
stream_chat/client.py

Report_ID is a UUID not an integer
https://github.com/GetStream/chat/blob/55c03aa1eb5b5ff1f9583a5944cf9d142e0715cc/types/moderation.go#L487

fix: report_id is is a uuid

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py

feat: add provider management

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py

feat: add device fields

---

stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/test_client.py

Adding two APIs which exist but are currently not in the python client, `mute_users` & `unmute_users`.

Add multi mute unmute

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/channel.py
stream_chat/client.py
stream_chat/tests/async_chat/conftest.py
stream_chat/tests/async_chat/test_client.py
stream_chat/tests/conftest.py
stream_chat/tests/test_client.py

added mute_users / unmute_users based on this outside contribution https://github.com/GetStream/stream-chat-python/pull/139

feat: Add multi user mute/unmute

---

stream_chat/client.py
stream_chat/tests/test_channel.py
stream_chat/tests/test_client.py

feat: pending messages

---

.github/workflows/ci.yml
setup.py

drop support for 3.7, add support for 3.11 and 3.12

---

stream_chat/async_chat/client.py
stream_chat/base/client.py
stream_chat/client.py

This adds support for undeleting messages that were previously soft-deleted

feat: add support for undeleting messages

---

.github/CODEOWNERS

[PBE-0] change code owner

---

.github/CODEOWNERS
stream_chat/base/client.py

[PBE-0] - Fix optional properties

---

stream_chat/tests/async_chat/test_query_threads.py
stream_chat/tests/test_query_threads.py

Fixing failing tests in query thread tests

Fix failing tests in query threads
