stream_chat/client.py, stream_chat/tests/test_client.py
In order to support user mute expiration, I've added an `options` keyword argument to the `mute_user` api method. When a `timeout` option given, an expiry time on the mute is set in the backend.
=> User mute expiration

stream_chat/channel.py, stream_chat/client.py, stream_chat/tests/conftest.py, stream_chat/tests/test_client.py
This PR fixes inconsistency of `sort` parameter of the query_members method and adds new ability to provide sort options as list to guarantee field order.
[Dict field order is only guaranteed since Python 3.7](https://stackoverflow.com/a/40007169/1039202)
=> [CHAT-1319] Added ability to provide sort options as list to guarantee field order

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_client.py
added sync and async endpoint for `check_sqs`, an endpoint to be used to verify credentials/settings for SQS push.
🚨  This depends on a (currently) unreleased backend feature, hence the failing tests. To be merged afterward.
related ruby SDK changes: https://github.com/GetStream/stream-chat-ruby/pull/32
=> added check sqs endpoint to sdk

CHANGELOG.md, stream_chat/__pkg__.py
- Update existing permission related API (/roles and /permissions endpoints)
=> Release 3.11.0

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py
Adds calls to get stream API similar to [get-stream-js](https://github.com/GetStream/stream-chat-js/) for:
- requesting channel export
- fetching channel export status
Implemented as:
```python
def export_channel(self, channel_id: str, channel_type: str, messages_since: str = None,
messages_until=None):
"""
Requests a channel export
"""
...
def export_channels(self, channels_data: list):
"""
Requests a channels export
"""
...
def get_export_channel_status(self, task_id: str):
"""
Retrieves status of export
"""
...
```
Example usage:
```python
>>> from stream_chat import StreamChat
>>> client = StreamChat(api_key=os.environ.get('STREAM_API_KEY', None), api_secret=os.environ.get('STREAM_API_SECRET', None))
>>> response = client.export_channel(my_channel_id, my_channel_type)
>>> response …
```
=> Add export_channel, get_export_channel_status

stream_chat/async_chat/client.py, stream_chat/client.py
* async client is set to less than server max idle
* sync client retries on bad conn (dns lookup, idle timeout, etc.), never on request
=> Tune session timeouts

stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py
Removing event_loop parameter as it seems unneccesary.
This came from a discussion here: https://github.com/GetStream/stream-chat-python/pull/86
=> ci: remove event_loop param from tests

.gitignore, stream_chat/async_chat/channel.py, stream_chat/base/channel.py, stream_chat/channel.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/test_channel.py
As part of CHAT-2700, add hide history support for add members API.
=> feat: add options to add members api

.github/workflows/ci.yml, .github/workflows/reviewdog.yml, .gitignore, MANIFEST.in, Makefile, README.md, pyproject.toml, setup.py, stream_chat/__init__.py, stream_chat/__pkg__.py, stream_chat/async_chat/__init__.py, stream_chat/async_chat/channel.py, stream_chat/async_chat/client.py, stream_chat/base/channel.py, stream_chat/base/client.py, stream_chat/base/exceptions.py, stream_chat/channel.py, stream_chat/client.py, stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/conftest.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py, stream_chat/types/stream_response.py
- Most importantly added type hints everywhere.
- Enforcing typing during the build with `mypy`
- removed docstrings from derived classes. docstrings are automatically inherited from the abstract class ‼️ no need to declare them twice.
- adding [py.typed file](https://www.python.org/dev/peps/pep-0561/) to the package
- removed unnecessary dependencies
- made testing logic much simpler. it was a bit weird, what was that long thing in setup.py? :)
- fix repository url in setup.py
- don't include test files in the published package ❗ 
- applying more `flake8` rules. Plus fixed two flake8 issues (`__all__` and `assert False`)
- added `flake8-bugbear` package, one of my favourite bug finder 🙂 
- updated release notes: let's upload wheels as well, not just sdists. wheels are generally better.
- …
=> feat: add type hints and mypy

.coveragerc, .github/CODEOWNERS, .github/workflows/ci.yml, .gitignore, Makefile, README.md, pyproject.toml, setup.py, stream_chat/__init__.py, stream_chat/async_chat/channel.py, stream_chat/async_chat/client.py, stream_chat/base/channel.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/conftest.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py, stream_chat/tests/utils.py, stream_chat/types/rate_limit.py, stream_chat/types/stream_response.py
- introduce a new response object: `StreamResponse`
- add ratelimit info, status code, response headers to the response object
- add `isort` code formatter (import statement sorting)
- remove 3.6 support as it's [end of life](https://endoflife.date/python)
- add myself and Ferhat to codeowners
- add ratelimit information to the readme
- stabilized unstable tests
=> Add rate limit to response, end of Py 3.6 support

.github/workflows/release.yml
This fixes the following error:
`error: invalid command 'bdist_wheel'`
=> ci: fix release job

stream_chat/async_chat/client.py
- set keepalive timeout to 59s
- there's no way to set it in `requests` (`urllib3`), because it doesn't contain [such feature](https://github.com/aio-libs/aiohttp/blob/58da3373a21211bbde21f1393475e73f53a5671d/aiohttp/connector.py#L295)
=> feat: set keepalive timeout to 59s

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_client.py
=> feat: add custom event endpoint

Makefile
print the test coverage to the console during builds
=> ci: print test coverage to console

stream_chat/tests/test_stream_response.py, stream_chat/types/stream_response.py
fixes https://github.com/GetStream/stream-chat-python/issues/125
=> Handle broken rate limit as best effort

stream_chat/async_chat/channel.py, stream_chat/base/channel.py, stream_chat/channel.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/test_channel.py
Added **options parameter to channel.create(), for example: `channel.create("john", hide_for_creator=True)`
=> feat: enable creation of channels with query options

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/test_client.py
For the regex blocklists we need to introduce a new `type` field in the DB to be able to distinguish between regular and regex blocklist (type). Therefore, when creating blocklist through the dashboard/SDK we need to pass the `type` field in the payload. In future, ideally this should support more types.
With the current change I extended the `create_blocklist()` method with an optional parameter that should pass the `type` field to the request payload
=> feat: Add type field support on create_blocklist()

stream_chat/async_chat/campaign.py, stream_chat/async_chat/client.py, stream_chat/async_chat/segment.py, stream_chat/base/campaign.py, stream_chat/base/client.py, stream_chat/base/segment.py, stream_chat/campaign.py, stream_chat/client.py, stream_chat/segment.py, stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_campaign.py, stream_chat/tests/async_chat/test_segment.py, stream_chat/tests/test_campaign.py, stream_chat/tests/test_segment.py, stream_chat/types/base.py, stream_chat/types/campaign.py, stream_chat/types/segment.py, stream_chat/types/stream_response.py
- https://stream-io.atlassian.net/browse/PBE-1321
=> [PBE-1321] support campaign endpoints

stream_chat/async_chat/campaign.py, stream_chat/async_chat/client.py, stream_chat/base/campaign.py, stream_chat/base/client.py, stream_chat/campaign.py, stream_chat/client.py, stream_chat/tests/async_chat/test_campaign.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_campaign.py, stream_chat/tests/test_client.py, stream_chat/types/campaign.py
=> [PBE-1392] add stop_at support

.github/workflows/ci.yml, setup.py, stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/conftest.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py
* Adds support and tests for the server side unread counts endpoint
* Adds (prepatory) support and tests for the new batch unread counts endpoint
* Fixes a known issue with a dependency https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html#known-issues
* Fixes deprecation warnings in old tests
=> add unread_count and unread_count_batch prep

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/test_client.py
=> feat: add support for show_deleted_message in getMessage

stream_chat/async_chat/client.py, stream_chat/async_chat/segment.py, stream_chat/base/client.py, stream_chat/base/segment.py, stream_chat/client.py, stream_chat/segment.py, stream_chat/types/segment.py
Related ticket:
- https://stream-io.atlassian.net/browse/PBE-1383
Related PRs:
- https://github.com/GetStream/chat/pull/6066
- https://github.com/GetStream/stream-chat-js/pull/1258
This PR enables support for sending a campaign:
- to all users
- to all channels where the sender is a member.
=> feat: support all_users & all_sender_channels for segment

setup.py, stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/test_client.py
Backend PR - https://github.com/GetStream/chat/pull/6301
Jira ticket - https://stream-io.atlassian.net/browse/PBE-3685
=> feat: new API endpoint query_message_history

stream_chat/async_chat/channel.py, stream_chat/base/channel.py, stream_chat/channel.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/test_channel.py
Add new api `mark_unread` for marking thread or message (`thread_id` // `message_id`)
=> feat: Add support for mark_unread msg or thread

stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py
- Added tests for the restricted visibility feature.
=> Added restricted_visibility tests

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py
Adds support for the async export users endpoint in the Chat API.
=> add support for async export users endpoint

.github/CODEOWNERS, stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_client.py
https://getstream.io/chat/docs/javascript/update_users/#deactivate-many-users
=> feat: added deactivate many users

stream_chat/async_chat/channel.py, stream_chat/base/channel.py, stream_chat/channel.py, stream_chat/tests/async_chat/conftest.py, stream_chat/tests/async_chat/test_channel.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/conftest.py, stream_chat/tests/test_channel.py, stream_chat/tests/test_client.py
=> fix: make sure we don't have left over users and channels

.gitignore, stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/base/query_threads.py, stream_chat/client.py, stream_chat/query_threads.py, stream_chat/tests/async_chat/test_query_threads.py, stream_chat/tests/test_query_threads.py
We added support of filter and sort parameter in QueryThreads endpoint. This MR adds the query_thread functionality to be used for client.
=> [CHA-794] Add query threads

stream_chat/async_chat/channel.py, stream_chat/async_chat/client.py, stream_chat/base/channel.py, stream_chat/base/client.py, stream_chat/channel.py, stream_chat/client.py, stream_chat/tests/async_chat/test_draft.py, stream_chat/tests/test_draft.py, stream_chat/types/draft.py
=> [CHA-607] add draft messages

stream_chat/async_chat/client.py, stream_chat/base/client.py, stream_chat/client.py, stream_chat/tests/async_chat/test_client.py, stream_chat/tests/test_client.py
- Linear Issue: https://linear.app/stream/issue/CHA-875/block-user-missing-in-python-sdk
=> fix: add block user methods
